controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/auth
    controller: App\Controller\AuthenticationController::login

auth:
    path: /api/auth
    methods: ['POST']
